---
title: "Download important data from figshare"
author: "Elisha Roberson"
date: "2020-09-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Project - Untreated + Skin + Muscle

```{r load_libraries}
library( here )
library( tidyverse )
```

```{r source}
source( file = here( "src", "shared_r_functions.R" ) )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	fig.path = paste0( figure_dir, "/" ),
	fig.keep = 'all',
	dpi = 300,
	fig.width = 11,
	fig.height = 8.5
)
```

```{r grab_files}
# download and rename files from figshare
# the links are stored in the shared fxns file as file_link_map
# its a list a things with link as first bin and destination file as bin 2

for ( idx in 1:length( file_link_map ) ) {
  url = file_link_map[[ idx ]][1] %>% as.character( . )
  dest = file_link_map[[ idx ]][2] %>% as.character( . )
  
  cat( paste0( "URL: ", url, "\n" ) )
  cat( paste0( "Path: ", dest, "\n" ) )
  
  download.file( url = url, destfile = dest, mode = 'wb' )
}
```

# Session info
```{r session_information}
Sys.time()

getwd()
  
sessionInfo()
```
