---
title: "Download necessary data"
date: "May 19, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries}
library( here )
library( tidyverse )
library( knitr )
```

```{r shared_functions}
source( here::here( "project_shared_fxns.R" ) )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	fig.path = paste0( path_to_figures, "/" ),
	fig.keep = 'all',
	dpi = 300,
	fig.width = 11,
	fig.height = 8.5 )
```

```{r grab_files}
# download and rename files from figshare
# the links are stored in the shared fxns file as file_link_map
# its a list a things with link as first bin and destination file as bin 2

for ( idx in 1:length( file_link_map ) ) {
  url = file_link_map[[ idx ]][1] %>% as.character( . )
  dest = file_link_map[[ idx ]][2] %>% as.character( . )
  
  cat( paste0( "URL: ", url, "\n" ) )
  cat( paste0( "Path: ", dest, "\n" ) )
  
  download.file( url = url, destfile = dest, mode = 'wb' )
}
```

```{r make_merged_counts}
# we got the data from figshare
# but that is by RGID
# we need to collapse it by rgsm

rgid_info <- read_csv( file =  project_rgid_path )

rgid_count_matrix <- read_csv( file = merged_count_rgid_path  ) %>%
  as.data.frame( . ) %>%
  column_to_rownames( "gene_id" ) %>%
  as.matrix( . )

rgsm_list <- pull( .data = rgid_info, var = RGSM ) %>%
  sort( . ) %>%
  unique( . )

rgsm_counts <- tibble( gene_id = rownames( rgid_count_matrix ) )

for ( idx in 1:length( rgsm_list ) ) {
  curr_rgsm <- rgsm_list[ idx ]
  
  rgid_list <- rgid_info %>%
    filter( RGSM == curr_rgsm ) %>%
    pull( RGID )
  
  rgsm_counts$tmp <- rgid_count_matrix[ , rgid_list, drop = FALSE ] %>%
    rowSums( x = ., na.rm = TRUE )
  
  colnames( rgsm_counts )[ dim( rgsm_counts )[2] ] = curr_rgsm
}

write_tsv( x = rgsm_counts, path = merged_count_path )
```

```{r session_information}
Sys.time()

getwd()
  
sessionInfo()
```
