---
title: "Running differential expression and getting normalized values"
author: "E. Roberson"
date: "April 27, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries}
library( here )
library( tidyverse )
library( DESeq2 )
library( knitr )
```

```{r shared_functions}
source( here::here( "project_shared_fxns.R" ) )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	fig.path = paste0( path_to_figures, "/" ),
	fig.keep = 'all',
	dpi = 300,
	fig.width = 11,
	fig.height = 8.5 )
```

```{r annotation}
ensembl = read_tsv( ensembl_annotation_path, col_names = c( 'gene_id', 'symbol' ), skip=1 ) %>%
  as.data.frame( . ) %>%
  unique( . )
```

```{r class_annotation}
sample_info <- read_csv( file = project_rgid_path ) %>%
	select( RGSM, Status, Sex ) %>%
	as.data.frame( . ) %>%
	unique( . ) %>%
	mutate( Status = factor( Status, levels=c( 'Control', 'JDM_Untreated', 'JDM_Inactive', 'JDM_Pre', 'JDM_Post' ) ) ) %>%
	mutate( Sex = factor( Sex, levels = c( 'F', 'M' ) ) )
rownames( sample_info ) = sample_info$RGSM

sample_info

with( data = sample_info, table( Status, Sex ) ) %>%
	kable( . )
```

```{r slurp_counts}
count.mat <- read_csv( file = merged_count_path, col_names = TRUE, col_types = cols( .default = col_integer(), gene_id = col_character() ) ) %>%
	as.data.frame( . ) %>%
	column_to_rownames( "gene_id" ) %>%
	as.matrix( . )
```

```{r prefilter_counts}
num_samples_gene_detected = apply( X = count.mat, MARGIN = 1, detect, cutoff = present_count_cutoff )

keeper.idx = which( num_samples_gene_detected >= min_detected_samples )

count.mat <- count.mat[ keeper.idx, which( colnames( count.mat ) %in% sample_info$RGSM ) ]
```

```{r run_deseq2}
design_matrix <- sample_info[ colnames( count.mat ) ,  ]

deseqObj <- DESeqDataSetFromMatrix( count.mat, design_matrix, ~ Sex + Status )

deseqObj <- DESeq( deseqObj, test="Wald", betaPrior=FALSE )
```

```{r extracting_untreat_control}
untreated_vs_control <- results( deseqObj, contrast = c( "Status", "JDM_Untreated", "Control" ) ) %>%
	format_deseq_results( ., ensembl )

write.csv( x = untreated_vs_control, file = deg_file_untreated_control, row.names = FALSE )

filter( untreated_vs_control, qval <= 0.05 & FC >= fold_change_for_graphs_y_gprofiler ) %>%
	write_csv( x = ., path = gprofiler_untreated_control_up )

filter( untreated_vs_control, qval <= 0.05 & FC <= ( -1 * fold_change_for_graphs_y_gprofiler ) ) %>%
	write_csv( x = ., path = gprofiler_untreated_control_down )

summarize_pretty_de_results( untreated_vs_control, fold_change_for_graphs_y_gprofiler )
```

```{r extracting_inactive_control}
inactive_vs_control <- results( deseqObj, contrast = c( "Status", "JDM_Inactive", "Control" ) ) %>%
	format_deseq_results( ., ensembl )

write.csv( x = inactive_vs_control, file = deg_file_inactive_control, row.names = FALSE )

filter( inactive_vs_control, qval <= 0.05 & FC >= fold_change_for_graphs_y_gprofiler ) %>%
	write_csv( x = ., path = gprofiler_inactive_control_up )

filter( inactive_vs_control, qval <= 0.05 & FC <= ( -1 * fold_change_for_graphs_y_gprofiler ) ) %>%
	write_csv( x = ., path = gprofiler_inactive_control_down )

summarize_pretty_de_results( inactive_vs_control, fold_change_for_graphs_y_gprofiler )
```

```{r extract_pre_vs_control}
pre_vs_control <- results( deseqObj, contrast = c( 'Status', 'JDM_Pre', 'Control' ) ) %>%
	format_deseq_results( ., ensembl )

write.csv( x = pre_vs_control, file = deg_file_prepsor_control, row.names = FALSE )

filter( pre_vs_control, qval < 0.05 & FC >= fold_change_for_graphs_y_gprofiler ) %>%
	write_csv( x = ., path = gprofiler_prepsor_control_up )

filter( pre_vs_control, qval < 0.05 & FC <= ( -1 * fold_change_for_graphs_y_gprofiler ) ) %>%
	write_csv( x = ., path = gprofiler_prepsor_control_down )

summarize_pretty_de_results( pre_vs_control, fold_change_for_graphs_y_gprofiler )
```

```{r extract_psor_vs_control}
psor_vs_control <- results ( deseqObj, contrast = c( 'Status', 'JDM_Post', 'Control' ) ) %>%
	format_deseq_results( ., ensembl )

write.csv( x = psor_vs_control, file = deg_file_withpsor_control, row.names = FALSE )

filter( psor_vs_control, qval < 0.05 & FC >= fold_change_for_graphs_y_gprofiler ) %>%
	write_csv( x = ., path = gprofiler_withpsor_control_up )

filter( psor_vs_control, qval < 0.05 & FC <= (-1 * fold_change_for_graphs_y_gprofiler ) ) %>%
	write_csv( x = ., path = gprofiler_withpsor_control_down )

summarize_pretty_de_results( psor_vs_control, fold_change_for_graphs_y_gprofiler )
```

```{r extracting_sex_effects}
design( deseqObj ) = ~ Status + Sex
deseqObj <- DESeq( deseqObj, full = ~ Status + Sex, reduced = ~Status, test = "LRT" )

female_vs_male <- results( deseqObj ) %>%
	format_deseq_results( ., ensembl ) %>%
	filter( qval < 0.05 )

write.csv( x = female_vs_male, file = genes_with_sex_linked_effect, row.names = FALSE )

summarize_pretty_de_results( female_vs_male, fold_change_for_graphs_y_gprofiler )
```

```{r extracting_logrratio}
assay( rlog( deseqObj, blind=FALSE ) ) %>%
	as.data.frame( . ) %>%
	rownames_to_column( "gene_id" ) %>%
	write.csv( x = ., file = sample_intensities_path, row.names = FALSE )
```

```{r session_information}
Sys.time()

getwd()
  
sessionInfo()
```
