---
title: "Paired-test for inactive / active samples -- female only & pre / post psoriasis"
author: "E. Roberson"
date: "April 27, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries}
library( here )
library( tidyverse )
library( DESeq2 )
library( knitr )
```

```{r shared_functions}
source( here::here( "project_shared_fxns.R" ) )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	fig.path = paste0( path_to_figures, "/" ),
	fig.keep = 'all',
	dpi = 300,
	fig.width = 11,
	fig.height = 8.5 )
```

```{r annotation}
ensembl = read_tsv( ensembl_annotation_path, col_names = c( 'gene_id', 'symbol' ), skip=1 ) %>%
  as.data.frame( . ) %>%
  unique( . )
```

# Samples untreated and reduced clinical activity

```{r class_annotation}
sample_info <- read_csv( file = project_rgid_path ) %>%
	filter( Sex == "F" ) %>%
	filter( ., Status %in% c( "JDM_Untreated", "JDM_Inactive" ) ) %>%
	filter( ., !( Status == "JDM_Untreated" & is.na( Individual ) ) ) %>%
	select( RGSM, Status, Individual ) %>%
	as.data.frame( . ) %>%
	unique( . ) %>%
	mutate( Status = factor( Status, levels=c( 'JDM_Inactive', 'JDM_Untreated' ) ) )

as.data.frame( sample_info )

rownames( sample_info ) = sample_info$RGSM
```

```{r slurp_counts}
count.mat <- read_tsv( file = merged_count_path,
                       col_names = TRUE,
                       col_types = cols( .default = col_integer(), gene_id = col_character() ) ) %>%
	as.data.frame( . ) %>%
	column_to_rownames( "gene_id" ) %>%
	as.matrix( . )

count.mat <- count.mat[ , sample_info$RGSM ]
```

```{r prefilter_counts}
num_samples_gene_detected = apply( X = count.mat, MARGIN = 1, detect, cutoff = present_count_cutoff )

keeper.idx = which( num_samples_gene_detected >= min_detected_samples )

count.mat <- count.mat[ keeper.idx, ]
```

```{r run_deseq2}
design_matrix <- sample_info[ colnames( count.mat ) ,  ]

deseqObj <- DESeqDataSetFromMatrix( count.mat, design_matrix, ~ Individual + Status )

deseqObj <- DESeq( deseqObj, test="Wald", betaPrior=FALSE )
```

```{r inactive_untreated_paired}
untreated_vs_inactive_paired <- results( deseqObj ) %>%
	format_deseq_results( ., ensembl )

write.csv( x = untreated_vs_inactive_paired, file = deg_file_inactive_untreated_paired, row.names = FALSE )

filter( untreated_vs_inactive_paired, qval <= 0.05 & FC >= fold_change_for_graphs_y_gprofiler ) %>%
	write_csv( x = ., path = gprofiler_inactive_untreated_paired_up )

filter( untreated_vs_inactive_paired, qval <= 0.05 & FC <= ( -1 * fold_change_for_graphs_y_gprofiler ) ) %>%
	write_csv( x = ., path = gprofiler_inactive_untreated_paired_down )

summarize_pretty_de_results( untreated_vs_inactive_paired, fold_change_for_graphs_y_gprofiler )
```

```{r extracting_logrratio}
assay( rlog( deseqObj, blind=FALSE ) ) %>%
	as.data.frame( . ) %>%
	rownames_to_column( "gene_id" ) %>%
	write.csv( x = ., file = paired_treated_samples_path, row.names = FALSE )
```

# Psoriasis samples
```{r just_in_case}
rm( list=ls() )

source( here::here( "project_shared_fxns.R" ) )
```

```{r reslurp_annotation}
ensembl = read_tsv( ensembl_annotation_path, col_names = c( 'gene_id', 'symbol' ), skip=1 ) %>%
  as.data.frame( . ) %>%
  unique( . )
```

```{r class_annotation_psoriasis}
sample_info <- read_csv( file = project_rgid_path ) %>%
	filter( ., Status %in% c( "JDM_Pre", "JDM_Post" ) ) %>%
	filter( ., !( is.na( Individual ) ) ) %>%
	select( RGSM, Status, Individual ) %>%
	as.data.frame( . ) %>%
	unique( . ) %>%
	mutate( Status = factor( Status, levels=c( 'JDM_Pre', 'JDM_Post' ) ) )

as.data.frame( sample_info )

rownames( sample_info ) = sample_info$RGSM
```

```{r slurp_counts_psoriasis}
count.mat <- read_tsv( file = merged_count_path, col_names = TRUE, col_types = cols( .default = col_integer(), gene_id = col_character() ) ) %>%
	as.data.frame( . ) %>%
	column_to_rownames( "gene_id" ) %>%
	as.matrix( . )

count.mat <- count.mat[ , sample_info$RGSM ]
```

```{r prefilter_counts_psoriasis}
num_samples_gene_detected = apply( X = count.mat, MARGIN = 1, detect, cutoff = present_count_cutoff )

keeper.idx = which( num_samples_gene_detected >= min_detected_samples )

count.mat <- count.mat[ keeper.idx, ]
```

```{r run_deseq2_psoriasis}
design_matrix <- sample_info[ colnames( count.mat ) ,  ]

deseqObj <- DESeqDataSetFromMatrix( count.mat, design_matrix, ~ Individual + Status )

deseqObj <- DESeq( deseqObj, test="Wald", betaPrior=FALSE )
```

```{r pre_post_paired}
pre_post_paired <- results( deseqObj ) %>%
	format_deseq_results( ., ensembl )

write.csv( x = pre_post_paired, file = deg_file_prepsor_psor_paired, row.names = FALSE )

filter( pre_post_paired, qval <= 0.05 & FC >= fold_change_for_graphs_y_gprofiler ) %>%
	write_csv( x = ., path = gprofiler_prepsor_psor_paired_up )

filter( pre_post_paired, qval <= 0.05 & FC <= ( -1 * fold_change_for_graphs_y_gprofiler ) ) %>%
	write_csv( x = ., path = gprofiler_prepsor_psor_paired_down )

summarize_pretty_de_results( pre_post_paired, fold_change_for_graphs_y_gprofiler )
```

```{r extracting_logrratio_psoriasis}
assay( rlog( deseqObj, blind=FALSE ) ) %>%
	as.data.frame( . ) %>%
	rownames_to_column( "gene_id" ) %>%
	write.csv( x = ., file = paired_pre_post_samples_path, row.names = FALSE )
```

# Wrap up

```{r session_information}
Sys.time()

getwd()
  
sessionInfo()
```
