---
title: "Volcano plots"
author: "E. Roberson"
date: "April 27, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries}
library( here )
library( tidyverse )
library( ggrepel )
library( cowplot )
library( UpSetR )
```

```{r shared_functions}
source( here::here( "project_shared_fxns.R" ) )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	fig.path = paste0( path_to_figures, "/" ),
	fig.keep = 'all',
	dpi = 300,
	fig.width = 11,
	fig.height = 8.5 )
```

```{r untreated_control_volcano}
untreated_control_volcano_plot <- read_csv( file = deg_file_untreated_control ) %>%
	as.data.frame( . ) %>%
	make_ggplot_volcano( deg_dataframe = ., case_name = "Untreated", control_name = "Control" )

untreated_control_volcano_plot
```

```{r inactive_control_volcano}
inactive_control_volcano_plot <- read_csv( file = deg_file_inactive_control ) %>%
	as.data.frame( . ) %>%
	make_ggplot_volcano( deg_dataframe = ., case_name = "Inactive", control_name = "Control" )
	
inactive_control_volcano_plot
```

```{r inactive_untreated_paired_volcano}
inactive_untreated_paired_volcano_plot <- read_csv( file = deg_file_inactive_untreated_paired ) %>%
	as.data.frame( . ) %>%
	make_ggplot_volcano( deg_dataframe = ., case_name = "Inactive", control_name = "Untreated" )
	
inactive_untreated_paired_volcano_plot
```

```{r pre_control_volcano}
pre_control_volcano <- read_csv( file = deg_file_prepsor_control ) %>%
  as.data.frame( . ) %>%
  make_ggplot_volcano( deg_dataframe = ., case_name = "PrePsoriasis", control_name = "Control" )
  
pre_control_volcano
```

```{r post_control_volcano}
post_control_volcano <- read_csv( file = deg_file_withpsor_control ) %>%
  as.data.frame( . ) %>%
  make_ggplot_volcano( deg_dataframe = ., case_name = "Psoriasis", control_name = "Control" )

post_control_volcano
```

```{r pre_vs_post_volcano}
pre_vs_post_volcano <- read_csv( file = deg_file_prepsor_psor_paired ) %>%
  as.data.frame( . ) %>%
  make_ggplot_volcano( deg_dataframe = ., case_name="Psoriasis", control_name = "PrePsoriasis" )

pre_vs_post_volcano
```

```{r joint_volcano_plots}
plot_grid( untreated_control_volcano_plot, inactive_untreated_paired_volcano_plot, align='h', labels=c( "A", "B" ), nrow=1 )

plot_grid( pre_control_volcano, pre_vs_post_volcano, align='h', labels = c( "A", "B" ) )
```

```{r untreated_deg_upset_chart}
untreated_v_control_gid <- read_csv( file = deg_file_untreated_control ) %>%
	filter( qval < 0.05 ) %>%
	pull( "gene_id" )

inactive_v_control_gid <- read_csv( file = deg_file_inactive_control ) %>%
	filter( qval < 0.05 ) %>%
	pull( "gene_id" )

inactive_untreated_paired_gid <- read_csv( file = deg_file_inactive_untreated_paired ) %>%
	filter( qval < 0.05 ) %>%
	pull( "gene_id" )

uniq_gid_list <- c( untreated_v_control_gid, inactive_untreated_paired_gid ) %>%
	unique( . )

input_for_upset <- data.frame( gene_id = uniq_gid_list ) %>%
	mutate( "Untreated-Control" = case_when(
		gene_id %in% untreated_v_control_gid ~ 1,
		TRUE ~ 0
	) ) %>%
	mutate( "Inactive-Untreated" = case_when(
		gene_id %in% inactive_untreated_paired_gid ~ 1,
		TRUE ~ 0
	) )

upset( input_for_upset, text.scale=c( 3, 3, 3, 2, 3, 3 ), point.size=5, line.size=2 )
```

```{r psoriasis_upset_chart}
prepsor_control_gid <- read_csv( file = deg_file_prepsor_control ) %>%
  filter( qval < 0.05 ) %>%
  pull( "gene_id" )

prepsor_psor_paired_gid <- read_csv( file = deg_file_prepsor_psor_paired ) %>%
  filter( qval < 0.05 ) %>%
  pull( "gene_id" )

psor_control_gid <- read_csv( file = deg_file_withpsor_control ) %>%
  filter( qval < 0.05 ) %>%
  pull( "gene_id" )

uniq_gid_list <- c( prepsor_control_gid, prepsor_psor_paired_gid )

input_for_upset <- data.frame( gene_id = uniq_gid_list ) %>%
  mutate( "PrePsoriasis-Control" = case_when(
    gene_id %in% prepsor_control_gid ~ 1,
    TRUE ~ 0 ) ) %>%
  mutate( "Psoriasis-PrePsoriasis" = case_when(
    gene_id %in% prepsor_psor_paired_gid ~ 1,
    TRUE ~ 0 ) )

upset( input_for_upset, text.scale=c( 3, 3, 3, 2, 3, 3 ), point.size=5, line.size=2 )
```

```{r untreated_psoriasis_upset_chart}
uniq_gid_list <- c( untreated_v_control_gid, inactive_v_control_gid, prepsor_control_gid,  psor_control_gid )

input_for_upset <- data.frame( gene_id = uniq_gid_list ) %>%
  mutate( "Untreated-Control" = case_when(
    gene_id %in% untreated_v_control_gid ~ 1,
    TRUE ~ 0 )) %>%
  mutate( "PrePsoriasis-Control" = case_when(
    gene_id %in% prepsor_control_gid ~ 1,
    TRUE ~ 0 )) %>%
  mutate( "Inactive-Control" = case_when(
    gene_id %in% inactive_v_control_gid ~ 1,
    TRUE ~ 0 )) %>%
  mutate( "Psoriasis-Control" = case_when(
    gene_id %in% psor_control_gid ~ 1,
    TRUE ~ 0 )) %>%
  write_csv( x = ., path = here::here( 'results' , "Diff_UpSet_Info.csv" ) )

upset( input_for_upset, text.scale=c( 3, 3, 3, 2, 3, 3 ), point.size=5, line.size=2 )

select( input_for_upset, -`PrePsoriasis-Control` ) %>%
  upset( data = ., text.scale=c( 3, 3, 3, 2, 3, 3 ), point.size=5, line.size=2 )
```

```{r session_information}
Sys.time()

getwd()
  
sessionInfo()
```
