---
title: "Individual gene plots"
author: "E. Roberson"
date: "April 27, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries}
library( here )
library( tidyverse )
library( reshape2 )
```

```{r shared_functions}
source( here::here( "project_shared_fxns.R" ) )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	fig.path = paste0( path_to_figures, "/" ),
	fig.keep = 'all',
	dpi = 300,
	fig.width = 11,
	fig.height = 8.5 )
```

```{r load_sample_info}
sample_info <- read_csv( file = project_rgid_path ) %>%
	select( RGSM, Status, Sex, Individual ) %>%
	as.data.frame( . ) %>%
	unique( . )
rownames( sample_info ) = sample_info$RGSM
```

```{r annotation}
ensembl = read_tsv( ensembl_annotation_path, col_names = c( 'gene_id', 'symbol' ), skip=1 ) %>%
  as.data.frame( . ) %>%
  unique( . )
```

```{r de_genes_load}
untreat_v_control_de_genes <- read_csv( file = deg_file_untreated_control )
inactive_v_control_de_genes <- read_csv( file = deg_file_inactive_control )
inactive_v_untreated_de_genes <- read_csv( file = deg_file_inactive_untreated_paired )
psor_v_control_de_genes <- read_csv( file = deg_file_withpsor_control )

untreat_v_control_de_geneids <- filter( untreat_v_control_de_genes, qval < 0.05 ) %>%
	pull( gene_id )

inactive_v_control_de_geneids <- filter( inactive_v_control_de_genes, qval < 0.05 ) %>%
	pull( gene_id )

inactive_v_untreated_de_geneids <- filter( inactive_v_untreated_de_genes, qval < 0.05 ) %>%
  pull( gene_id )

psor_v_control_de_geneids <- filter( psor_v_control_de_genes, qval < 0.05 ) %>%
  pull( gene_id )

all_de_geneids <- c( untreat_v_control_de_geneids, inactive_v_control_de_geneids, inactive_v_untreated_de_geneids, psor_v_control_de_geneids ) %>%
	unique( . )
```

```{r read_values}
rlog <- read_csv( file = sample_intensities_path, col_names = TRUE, col_types = cols( .default = 'd', gene_id = 'c' ) ) %>%
	filter( gene_id %in% all_de_geneids ) %>%
	melt( . ) %>%
	mutate( RGSM = variable ) %>%
	mutate( rlog = value ) %>%
	select( -variable, -value ) %>%
	mutate( RGSM = as.character( RGSM ) ) %>%
	mutate( status = sample_info[ RGSM, "Status" ] ) %>%
	mutate( status = as.character( status ) ) %>%
	mutate( status = str_replace( string = status, pattern = "JDM_", replacement = "" ) ) %>%
  mutate( status = str_replace( string = status, pattern = "Post", replacement = "Psor" ) ) %>%
	mutate( status = factor( status, levels=c( "Control", "Untreated", "Inactive", "Pre", "Psor" ) ) ) %>%
	mutate( sex = sample_info[ RGSM, "Sex" ] ) %>%
	mutate( individual = sample_info[ RGSM, "Individual" ] ) %>%
	mutate( manual_x_position = case_when(
		status == "Untreated" ~ 1.8,
		status == "Inactive" ~ 3.0,
		TRUE ~ 1.0 ) )
```

```{r print_genes}
# all_de_geneids
for ( idx in 1:length( all_de_geneids ) ) {
  current_gene <- all_de_geneids[ idx ]
  
  current_symbol <- filter( .data = ensembl, gene_id == current_gene ) %>%
    pull( .data = ., symbol )
  
  title_text <- paste0( current_gene, " (", current_symbol, ")\n" )
  
  file_text <- paste0( current_symbol, "_", current_gene )
  
  snip <- rlog %>%
    filter( gene_id == current_gene )
  
  for_lines = filter( snip, !is.na( individual ) ) %>%
  	mutate( status = as.character( status ) ) %>%
  	mutate( status = factor( status, levels = c( "Control", "Untreated", "Inactive" ) ) )
  
  obj <- ggplot( data = snip, mapping = aes( x=status, y=rlog ) ) +
  	theme_bw() +
  	scale_colour_manual( values = colorBlindPalette ) +
  	stat_summary( fun.y = mean, fun.ymin = mean, fun.ymax = mean, geom = 'crossbar', width=0.5 ) +
  	geom_point( size = 5, aes( shape=sex, colour=sex  ), alpha = 0.8 ) +
  	geom_line( data = subset( snip, !is.na( individual ) ), mapping = aes( group = individual ) ) +
  	geom_point( size = 5, aes( shape=sex, colour=sex  ), alpha = 0.8 ) +
  	xlab( "\nStatus" ) +
  	ylab( "Normalized expression (rlog)\n" ) +
    ggtitle( title_text ) +
    theme( legend.position = "top" ) +
    gg_bigger_texts +
  	gg_center_title
  
  jpeg( file=file.path( path_to_gene_figures, paste0( file_text, ".jpeg" ) ), width=1280, height=1024, res=75 )
  print( obj )
  dev.off()
}
```

```{r session_information}
Sys.time()

getwd()
  
sessionInfo()
```
