---
title: "PCA plots"
author: "E. Roberson"
date: "April 27, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries}
library( here )
library( tidyverse )
library( ggrepel )
```

```{r shared_functions}
source( here::here( "project_shared_fxns.R" ) )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	fig.path = paste0( path_to_figures, "/" ),
	fig.keep = 'all',
	dpi = 300,
	fig.width = 11,
	fig.height = 8.5 )
```

```{r constants}
fc_cutoff <- 2.0
```

```{r load_gene_lists}
untreated_v_control <- read_csv( file = deg_file_untreated_control ) %>%
	filter( qval < 0.05 & abs( FC ) >= fc_cutoff ) %>%
	pull( gene_id )

inactive_v_untreated <- read_csv( file = deg_file_inactive_untreated_paired ) %>%
	filter( qval < 0.05  & abs( FC ) >= fc_cutoff ) %>%
	pull( gene_id )

pre_v_control <- read_csv( file = deg_file_prepsor_control ) %>%
  filter( qval < 0.05 & abs( FC ) >= fc_cutoff ) %>%
  pull( gene_id )

psor_v_control <- read_csv( file = deg_file_withpsor_control ) %>%
  filter( qval < 0.05 & abs( FC ) >= fc_cutoff ) %>%
  pull( gene_id )

status_de_gene_ids <- unique( untreated_v_control )
#	unique( . )
	
sex_linked_genes <- read_csv( file = genes_with_sex_linked_effect ) %>%
	filter( qval < 0.05 & abs( FC ) >= fc_cutoff ) %>%
	pull( gene_id )
```

```{r class_annotation}
sample_info <- read_csv( file = project_rgid_path ) %>%
	filter( !is.na( RGSM ) ) %>%
	select( ., -Tissue, -RGID ) %>%
	as.data.frame( . ) %>%
	unique( . ) %>%
  filter( Status %in% c( "Control", "JDM_Untreated", "JDM_Inactive" ) ) %>%
	mutate( Status = factor( Status, levels=c( 'Control', 'JDM_Untreated', 'JDM_Inactive' ) ) )
rownames( sample_info ) = sample_info$RGSM

as.data.frame( sample_info )
```

```{r load_rlog}
rlog.df <- read_csv( file = sample_intensities_path, col_names = TRUE, col_types = cols( .default = 'd', gene_id = 'c' ) )

rlog.mat <- rlog.df %>%
	as.data.frame( . ) %>%
	column_to_rownames( "gene_id" ) %>%
	as.matrix( . )
```

```{r sex_pca}
first_plot_pc <- 1
second_plot_pc <- 2

# Run PCA
pca.mat <- rlog.mat[ sex_linked_genes , ]

pca.out <- prcomp( x = t( pca.mat ), scale. = TRUE )
percent_variance <- round( pca.out$sdev^2 / sum( pca.out$sdev^2 )* 100.0, 2 )

# Add demographics
pca.coords <- pca.out$x %>%
	as.data.frame( . ) %>%
	rownames_to_column( ., "RGSM" ) %>%
	merge( sample_info, ., by = "RGSM" )

# Add clusters
clusters <- select( pca.coords, PC1, PC2 ) %>%
	kmeans( x = ., centers = 2 )

pca.coords$cluster_num <- clusters$cluster
pca.coords$cluster <- LETTERS[ clusters$cluster ]

cluster_counts <- with( pca.coords, table( cluster ) ) %>%
  as.data.frame( . )
rownames( cluster_counts ) = cluster_counts$cluster

sex_fraction <- select( .data = pca.coords, Sex, cluster ) %>%
  with( data = ., table( cluster, Sex ) ) %>%
  as.data.frame( . ) %>%
  mutate( .data = ., FractionF = Freq / cluster_counts[ cluster, "Freq" ] ) %>%
  filter( .data = ., Sex == "F" )
rownames( sex_fraction ) = sex_fraction$cluster

female_cluster <- ifelse( sex_fraction[ 'A', 'FractionF' ] > sex_fraction[ 'B', 'FractionF' ], 'A', 'B' )
male_cluster <- ifelse( female_cluster == 'A', 'B', 'A' )

pca.coords <- pca.coords %>%
	mutate( sex_classification = case_when(
		Sex == 'F' & cluster != female_cluster ~ "Incorrect",
		Sex == 'M' & cluster != male_cluster ~ "Incorrect",
		TRUE ~ "Correct"
	))

pca.coords %>%
	mutate( GeneticSex = case_when(
		cluster == female_cluster ~ "F",
		cluster == male_cluster ~ "M"
	)) %>%
	mutate( .data = ., SexCluster = cluster ) %>%
	mutate( .data = ., SpecifiedSex = Sex ) %>%
	select( .data = ., RGSM, SpecifiedSex, SexCluster, GeneticSex ) %>%
	write_csv( x = ., path = sex_from_expression_path )

pca.coords <- pca.coords %>%
	mutate( Sex = factor( Sex ) ) %>%
	mutate( cluster = factor( cluster ) ) %>%
	mutate( plot_label = str_replace( string = RGSM, pattern = "Pachman_", replacement = "" ) )

# Plot dimension names
x_dim_name <- paste0( "PC", first_plot_pc, " (", percent_variance[first_plot_pc], "%)" )
y_dim_name <- paste0( "PC", second_plot_pc, " (", percent_variance[second_plot_pc], "%)" )

ggplot( data = pca.coords, mapping = aes( x=PC1, y=PC2, shape=Sex, colour=cluster ) ) +
	theme_bw() +
	scale_color_manual( values = c( 'black', 'grey' ) ) +
	geom_point( size=5 ) +
	gg_bigger_texts +
	gg_center_title +
	xlab( x_dim_name ) +
	ylab( y_dim_name ) +
	ggtitle( "Sex classification by PCA" ) +
	theme( legend.position = 'top' ) +
	geom_text_repel( data = subset( pca.coords, sex_classification == "Incorrect" ), colour = "black", aes( label = plot_label ) )
```

```{r disease_status_pca_both_gene_sets}
first_plot_pc <- 1
second_plot_pc <- 2

# Run PCA
pca.mat <- rlog.mat[ status_de_gene_ids , ]

pca.out <- prcomp( x = t( pca.mat ), scale. = TRUE )
percent_variance <- round( pca.out$sdev^2 / sum( pca.out$sdev^2 )* 100.0, 2 )

# Add demographics
pca.coords <- pca.out$x %>%
	as.data.frame( . ) %>%
	rownames_to_column( ., "RGSM" ) %>%
	merge( sample_info, ., by = "RGSM" )

# Plot dimension names
x_dim_name <- paste0( "PC", first_plot_pc, " (", percent_variance[first_plot_pc], "%)" )
y_dim_name <- paste0( "PC", second_plot_pc, " (", percent_variance[second_plot_pc], "%)" )

ggplot( data = pca.coords, mapping = aes( x=PC1, y=PC2, shape=Status, colour=Status ) ) +
	theme_bw() +
	#scale_color_manual( values = severityPalette[ c(1,2,4,3,5) ] ) +
	#scale_color_manual( values = c( 'black', reds5Palette[3] ). ) +
  scale_color_manual( values = c( 'black', reds3Palette[3], reds3Palette[2] ) ) +
	geom_point( size=5 ) +
	gg_bigger_texts +
	gg_center_title +
	xlab( x_dim_name ) +
	ylab( y_dim_name ) +
	ggtitle( "Disease status classification by PCA" ) # +
	#theme( legend.position = "top" )
```

```{r session_information}
Sys.time()

getwd()
  
sessionInfo()
```
