---
title: "Work with gProfiler data"
author: "E. Roberson"
date: "April 27, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries}
library( here )
library( tidyverse )
library( cowplot )
library( purrr )
```

```{r shared_functions}
source( here::here( "project_shared_fxns.R" ) )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	fig.path = paste0( path_to_figures, "/" ),
	fig.keep = 'all',
	dpi = 300,
	fig.width = 11,
	fig.height = 8.5 )
```

# Setup

```{r notes}

# Note: depending on settings when running gProfiler, may need 
# to do some filtering of the results to get rid of categories
# that we don't really care about.
# filter( type %in% c( 'cor', 'BP', 'CC', 'reac', 'rea', 'keg', 'tf' ) ) %>%

# contrasts
# untreated_v_control
# inactive_v_control
# untreated_v_inactive_paired
# pre_v_control
# psor_v_control ## up only
```

```{r annotation}
ensembl = read_tsv( ensembl_annotation_path, col_names = c( 'gene_id', 'symbol' ), skip=1 ) %>%
  as.data.frame( . ) %>%
  unique( . )
rownames( ensembl ) = ensembl$gene_id
```

# Untreated vs. Control
```{r untreated_vs_control}
# has to be consistent between files
contrast <- "untreated_v_control"

# Decreased genes
down.fname <- dir( path_to_gprofiles, pattern = paste0( "gprofiler_results_[0-9]+_", contrast, "_down_v00.txt" ) )
down.fname

down.fpath <- file.path( path_to_gprofiles, down.fname )
down.fpath
stopifnot( file.exists( down.fpath ) )

full.down.tbl <- parse_raw_gprofile( gprof_file_path = down.fpath, symbol_df = ensembl )
  
# Increased genes
up.fname <- dir( path_to_gprofiles, pattern = paste0( "gprofiler_results_[0-9]+_", contrast, "_up_v00.txt" ) )
up.fname

up.fpath <- file.path( path_to_gprofiles, up.fname )
up.fpath
stopifnot( file.exists( up.fpath ) )

full.up.tbl <- parse_raw_gprofile( gprof_file_path = up.fpath, symbol_df = ensembl )

####################
# make the figures #
####################
#gprofiler_ggplot_bonanza <- function( full.down.tbl, full.up.tbl, contrast_name, gprofile_figure_path )
untreat_v_control_plot_list <- gprofiler_ggplot_bonanza( full.down.tbl = full.down.tbl, full.up.tbl = full.up.tbl, contrast_name = contrast_name, gprofile_figure_path = path_to_gprofiler_figures )

curr_up = untreat_v_control_plot_list[[ 'up' ]]
curr_down = untreat_v_control_plot_list[[ 'down' ]]

save( curr_up, file = file.path( path_to_saved_objects, "untreated_v_control_up_pathway.RData" ) )

save( curr_down, file = file.path( path_to_saved_objects, "untreated_v_control_down_pathway.RData" ) )
```

# Inactive vs. Control
```{r untreated_vs_control_load}
# has to be consistent between files
contrast <- "inactive_v_control"

# Decreased genes
down.fname <- dir( path_to_gprofiles, pattern = paste0( "gprofiler_results_[0-9]+_", contrast, "_down_v00.txt" ) )
down.fname

down.fpath <- file.path( path_to_gprofiles, down.fname )
down.fpath
stopifnot( file.exists( down.fpath ) )

full.down.tbl <- parse_raw_gprofile( gprof_file_path = down.fpath, symbol_df = ensembl )
  
# Increased genes
up.fname <- dir( path_to_gprofiles, pattern = paste0( "gprofiler_results_[0-9]+_", contrast, "_up_v00.txt" ) )
up.fname

up.fpath <- file.path( path_to_gprofiles, up.fname )
up.fpath
stopifnot( file.exists( up.fpath ) )

full.up.tbl <- parse_raw_gprofile( gprof_file_path = up.fpath, symbol_df = ensembl )

####################
# make the figures #
####################
#gprofiler_ggplot_bonanza <- function( full.down.tbl, full.up.tbl, contrast_name, gprofile_figure_path )
gprofiler_ggplot_bonanza( full.down.tbl = full.down.tbl, full.up.tbl = full.up.tbl, contrast_name = contrast_name, gprofile_figure_path = path_to_gprofiler_figures )
```

# Inactive vs. Untreated
```{r untreated_v_inactive_paired}
# has to be consistent between files
contrast <- "untreated_v_inactive_paired"

# Decreased genes
down.fname <- dir( path_to_gprofiles, pattern = paste0( "gprofiler_results_[0-9]+_", contrast, "_down_v00.txt" ) )
down.fname

down.fpath <- file.path( path_to_gprofiles, down.fname )
down.fpath
stopifnot( file.exists( down.fpath ) )

full.down.tbl <- parse_raw_gprofile( gprof_file_path = down.fpath, symbol_df = ensembl )
  
# Increased genes
up.fname <- dir( path_to_gprofiles, pattern = paste0( "gprofiler_results_[0-9]+_", contrast, "_up_v00.txt" ) )
up.fname

up.fpath <- file.path( path_to_gprofiles, up.fname )
up.fpath
stopifnot( file.exists( up.fpath ) )

full.up.tbl <- parse_raw_gprofile( gprof_file_path = up.fpath, symbol_df = ensembl )

####################
# make the figures #
####################
#gprofiler_ggplot_bonanza <- function( full.down.tbl, full.up.tbl, contrast_name, gprofile_figure_path )
untreat_v_inactive_plot_list <- gprofiler_ggplot_bonanza( full.down.tbl = full.down.tbl, full.up.tbl = full.up.tbl, contrast_name = contrast_name, gprofile_figure_path = path_to_gprofiler_figures )

curr_up = untreat_v_inactive_plot_list[[ 'up' ]]
curr_down = untreat_v_inactive_plot_list[[ 'down' ]]

save( curr_up, file = file.path( path_to_saved_objects, "untreated_v_inactive_up_pathway.RData" ) )

save( curr_down, file = file.path( path_to_saved_objects, "untreated_v_inactive_down_pathway.RData" ) )
```

# PrePsor vs. Control
```{r pre_v_control}
# has to be consistent between files
contrast <- "pre_v_control"

# Decreased genes
down.fname <- dir( path_to_gprofiles, pattern = paste0( "gprofiler_results_[0-9]+_", contrast, "_down_v00.txt" ) )
down.fname

down.fpath <- file.path( path_to_gprofiles, down.fname )
down.fpath
stopifnot( file.exists( down.fpath ) )

full.down.tbl <- parse_raw_gprofile( gprof_file_path = down.fpath, symbol_df = ensembl )
  
# Increased genes
up.fname <- dir( path_to_gprofiles, pattern = paste0( "gprofiler_results_[0-9]+_", contrast, "_up_v00.txt" ) )
up.fname

up.fpath <- file.path( path_to_gprofiles, up.fname )
up.fpath
stopifnot( file.exists( up.fpath ) )

full.up.tbl <- parse_raw_gprofile( gprof_file_path = up.fpath, symbol_df = ensembl )

####################
# make the figures #
####################
#gprofiler_ggplot_bonanza <- function( full.down.tbl, full.up.tbl, contrast_name, gprofile_figure_path )
gprofiler_ggplot_bonanza( full.down.tbl = full.down.tbl, full.up.tbl = full.up.tbl, contrast_name = contrast_name, gprofile_figure_path = path_to_gprofiler_figures )
```

# Psor vs. Control
```{r psor_v_control}
# has to be consistent between files
contrast <- "psor_v_control"

# Decreased genes
down.fname <- dir( path_to_gprofiles, pattern = paste0( "gprofiler_results_[0-9]+_", contrast, "_down_v00.txt" ) )
down.fname

down.fpath <- file.path( path_to_gprofiles, down.fname )
down.fpath
stopifnot( file.exists( down.fpath ) )

full.down.tbl <- NA # parse_raw_gprofile( gprof_file_path = down.fpath, symbol_df = ensembl )
  
# Increased genes
up.fname <- dir( path_to_gprofiles, pattern = paste0( "gprofiler_results_[0-9]+_", contrast, "_up_v00.txt" ) )
up.fname

up.fpath <- file.path( path_to_gprofiles, up.fname )
up.fpath
stopifnot( file.exists( up.fpath ) )

full.up.tbl <- parse_raw_gprofile( gprof_file_path = up.fpath, symbol_df = ensembl )

####################
# make the figures #
####################
#gprofiler_ggplot_bonanza <- function( full.down.tbl, full.up.tbl, contrast_name, gprofile_figure_path )
gprofiler_ggplot_bonanza( full.down.tbl = full.down.tbl, full.up.tbl = full.up.tbl, contrast_name = contrast_name, gprofile_figure_path = path_to_gprofiler_figures )
```

```{r session_information}
Sys.time()

getwd()
  
sessionInfo()
```
