---
title: "Running WGCNA on samples"
author: "E. Roberson"
date: "October 8, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries}
library( here )
library( tidyverse )
library( reshape2 )
library( cowplot )
library( UpSetR )
```

```{r shared_functions}
source( here::here( "project_shared_fxns.R" ) )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	fig.path = paste0( path_to_figures, "/" ),
	fig.keep = 'all',
	dpi = 300,
	fig.width = 11,
	fig.height = 8.5 )
```

```{r input}
# DEG untreated / control
deg <- read_csv( deg_file_untreated_control ) %>%
  filter( qval < 0.05 ) %>%
  mutate( DEG_Untreated = case_when( 
    FC > 0.0 ~ "Up",
    FC < 0.0 ~ "Down",
    TRUE ~ "Error" ) ) %>%
  select( gene_id, symbol, DEG_Untreated )

# Correlation
dasm <- read_csv( file.path( wgcna_output_path, "WGCNA_table_DASM.csv" ) ) %>%
  filter( p.GS.Status < 0.05 ) %>%
  select( gene_id:symbol ) %>%
  select( -moduleColor ) %>%
  mutate( DASM.Correlation = GS.corr.Status ) %>%
  mutate( DASM.pvalue = p.GS.Status ) %>%
  select( gene_id, symbol, DASM.Correlation, DASM.pvalue )

dast <- read_csv( file.path( wgcna_output_path, "WGCNA_table_DAST.csv " ) ) %>%
  filter( p.GS.Status < 0.05 ) %>%
  select( gene_id:symbol ) %>%
  select( -moduleColor ) %>%
  mutate( DAST.Correlation = GS.corr.Status ) %>%
  mutate( DAST.pvalue = p.GS.Status ) %>%
  select( gene_id, symbol, DAST.Correlation, DAST.pvalue )

# Inactive / active status
inactive_change <- read_csv( here::here( 'results', 'deg_untreated_vs_inactive_paired_with_treateffect.csv' ) ) %>%
  select( gene_id, TreatmentEffect )
```

```{r write}
combo <- dasm %>%
  as.data.frame( . ) %>%
  merge( ., as.data.frame( dast ), all = TRUE, by = c( 'gene_id', 'symbol' ) ) %>%
  merge( ., deg, all.x = TRUE ) %>%
  merge( ., inactive_change, all.x = TRUE ) %>%
  arrange( DASM.pvalue, DAST.pvalue ) %>%
  write_csv( x = ., path = here::here( 'results', 'DASM_y_DAST_table.csv' ) )

combo = combo %>%
  mutate( SignifDASM = case_when( DASM.pvalue < 0.05 ~ "Yes", TRUE ~ "No" ) ) %>%
  mutate( SignifDAST = case_when( DAST.pvalue < 0.05 ~ "Yes", TRUE ~ "No" ) ) %>%
  mutate( CorrTypeDASM = case_when( DASM.Correlation < 0.0 ~ "Negative", TRUE ~ "Positive" ) ) %>%
  mutate( CorrTypeDAST = case_when( DAST.Correlation < 0.0 ~ "Negative", TRUE ~ "Positive" ) )

with( data = combo, table( SignifDASM, SignifDAST ) )

# DASM
with( data = combo, table( CorrTypeDASM ) )

# DAST
with( data = combo, table( CorrTypeDAST ) )
```

```{r corr_upset}
pos_dasm <- filter( .data = combo, SignifDASM == "Yes" & CorrTypeDASM == "Positive" ) %>%
  pull( .data = ., gene_id )

neg_dasm<- filter( .data = combo, SignifDASM == "Yes" & CorrTypeDASM == "Negative" ) %>%
  pull( .data = ., gene_id )

pos_dast<- filter( .data = combo, SignifDAST == "Yes" & CorrTypeDASM == "Positive" ) %>%
  pull( .data = ., gene_id )

neg_dast<- filter( .data = combo, SignifDAST == "Yes" & CorrTypeDASM == "Negative" ) %>%
  pull( .data = ., gene_id )

all_corr_ids <- c( pos_dasm, neg_dasm, pos_dast, neg_dast ) %>%
  sort( . ) %>%
  unique( . )

correlation_upset_df <- data.frame( gene_id = all_corr_ids ) %>%
  mutate( .data = ., PosDASM = case_when(
    gene_id %in% pos_dasm ~ 1,
    TRUE ~ 0 ) ) %>%
  mutate( .data = ., NegDASM = case_when(
    gene_id %in% neg_dasm ~ 1,
    TRUE ~ 0 ) ) %>%
  mutate( .data = ., PosDAST = case_when(
    gene_id %in% pos_dast ~ 1,
    TRUE ~ 0 ) ) %>%
  mutate( .data = ., NegDAST = case_when(
    gene_id %in% neg_dast ~ 1,
    TRUE ~ 0 ) ) %>%
  column_to_rownames( var = "gene_id" )

upset( correlation_upset_df, text.scale = c( 3, 3, 3, 2, 3, 3 ), point.size = 5, line.size = 2, nintersects = NA )
```

Total correlated genes: `r length( all_corr_ids )`

## Update table for Gephi
```{r update_for_gephi_input}
in_list <- dir( wgcna_output_path, pattern = "^GephiInput-edges" )

for( idx in 1:length( in_list ) ) {
  curr_fname <- in_list[ idx ]
  new_fname <- str_replace( string = curr_fname, pattern = "\\.[a-z]+", replacement = "" )
  
  input <- read_tsv( file = file.path( wgcna_output_path, curr_fname ), col_names = TRUE )
  
  input %>%
    mutate( .data = ., Source = fromNode ) %>%
    mutate( .data = ., Target = toNode ) %>%
    select( .data = ., Source, Target, weight ) %>%
    write_csv( x = ., path = file.path( wgcna_output_path, paste0( new_fname, ".csv" ) ) )
}
```

```{r session_information}
Sys.time()

getwd()
  
sessionInfo()
```
